name: "Booklets Builder"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-booklets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v3

      - name: Refresh Packages
        run: sudo apt-fast -y update
      
      - name: Install Dependencies
        run: xargs -a dependencies sudo apt-fast install -y

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      
      - name: Python Install Dependencies
        run: pip install -r docs/requirements.txt

      - name: Build Booklets
        env:
          SPHINXOPTS: "-D html_context.commit=${{ github.sha }} -D version=latest -A display_github=true -A github_user=${{ github.repository_owner }} -A github_repo=${{ github.event.repository.name }} -A github_version=${{ github.ref_name }} -A conf_py_path=/docs/source/"
        run: |
          cd docs
          make booklets
          cd ..

      - name: Archive Booklets
        env:
          PR_NUMBER: ${{ github.event.number }}
          ID:  ${{ github.run_attempt }}
        uses: actions/upload-artifact@v3
        with:
          name: FTCDOCS-Booklets
          path: |
            docs/build/booklets/*.pdf
          if-no-files-found: error